### ISSUE TITLE
Library XML to Excel crashes program

### ISSUE THREAD

**Issue by craigjames2** [iriusrisk/iriusrisktoolkitui#33]
1. I downloaded a selection of built-in libraries from IriusRisk
2. I used the iriusrisktoolkit program in a virtual environment and selected option 1
3. I navigated to the downloaded library xml and clicked "submit"
4. This error occurred: 
Traceback (most recent call last):
  File "[path placeholder]\iriusrisktoolkitui\IriusRiskToolKitUI.py", line 1193, in <module>
    main()
  File "[path placeholder]\iriusrisktoolkitui\IriusRiskToolKitUI.py", line 1166, in main
    results, links = checkIfConvertXmlToExcel(event, results, home, links)
  File "[path placeholder]\iriusrisktoolkitui\IriusRiskToolKitUI.py", line 721, in checkIfConvertXmlToExcel
    link = convertXmlToExcel(
  File "[path placeholder]\iriusrisktoolkitui\src\convertXmlToExcel.py", line 538, in convertXmlToExcel
    (data,info, rules)=getDataFromXml(str(xmlPath))
  File "[path placeholder]\iriusrisktoolkitui\src\convertXmlToExcel.py", line 203, in getDataFromXml
    table.extend(getAllDataFromRiskPatterns(rootClass))
  File "[path placeholder]\iriusrisktoolkitui\src\convertXmlToExcel.py", line 117, in getAllDataFromRiskPatterns
    for riskPattern in riskPatterns.get_component():
AttributeError: 'NoneType' object has no attribute 'get_component'

This error occurs on "generate html from xml" as well.

**Comment by jesperon** [comment]
Hi @craigjames2! 
Thanks for the heads-up. 
Unfortunately, this repository is no longer supported and won't be updated anymore. However, it should still work with libraries created from versions between 3.6.0 and 3.13.0.
Kind regards.

**Comment by stephendv1** [comment]
@craigjames2 if you need to use this toolkit with v4.x of IriusRisk please get in touch with our support team, they will point you in the direction of a newer tool.

**Comment by craigjames2** [comment]
Thank you! Ken Chau has been helping me with this.
